spring:
  application:
    name: zuul-edge-server
  profiles:
    active: localhost

info:
  component: Zuul Edge Server

---
spring:
  config:
    activate:
      on-profile: localhost


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

ribbon:
  eureka:
    enabled: true

server:
  port: 8762

zuul:
  routes:
    product-service:
      path: /api/v1.0/product/**
      serviceId: product-service
      strip-prefix: false


